#!/bin/bash

domain=$1
mydate=`date +%Y%m%d`

echo -e "\$TTL 604800
@	IN	SOA	ns.$domain.niels-delanghe.sb.uclllabs.be. root.$domain.niels-delanghe.sb.uclllabs.be.(
			$mydate"1"	; Serial
			604800		; Refresh
			600		; Retry
			600		; Expire
			604800)		; Negative Cache TTl
;

@	IN	NS	ns.$domain.niels-delanghe.sb.uclllabs.be.
@	IN	NS	ns.niels-delanghe.sb.uclllabs.be.

ns	IN	A	193.191.177.165
@	IN	A	193.191.177.165 " > /etc/bind/zones/db.$domain.niels-delanghe.sb.uclllabs.be

echo "Add zone"
echo -e "zone \"$domain.niels-delanghe.sb.uclllabs.be\" {
	type master;
	file \"/etc/bind/zones/db.$domain.niels-delanghe.sb.uclllabs.be\";
	notify yes;
};
" >> /etc/bind/named.conf.local

echo -e "$domain	IN	NS	ns.niels-delanghe.sb.uclllabs.be." >> /etc/bind/zones/db.niels-delanghe.sb.uclllabs.be

serialline=$(grep "Serial" /etc/bind/zones/db.niels-delanghe.sb.uclllabs.be)
serialnumber=$(echo $serialline | cut -d \; -f 1)
((serialnumber++))
newserial="$serialnumber	; Serial"
echo $newserial;
sed -i "s/.*Serial.*/\t\t\t	$newserial/g" /etc/bind/zones/db.niels-delanghe.sb.uclllabs.be
echo -e "serial updated, restarting bind9"

systemctl restart bind9

echo "Done."
